### ISSUE TITLE
Timezone aware convert_to_datetime

### ISSUE THREAD

**Issue by dadosch** [stephan192/hochwasserportal#43]
When parsing and handling date and time, the timezone is ignored, and HA uses UTC internally, which means that a wrong value is displayed later. 

For example, a value of "03.01.2024 23:45 MEZ" from the BW API gets parsed using convert_to_datetime("03.01.2024 23:45", "%d.%m.%Y%H:%M"), this then creates a python datetime object, which HA assumes to be UTC. When displayed in the UI it assumes it is UTC and converts it to CET, to become "4. Januar 2024 um 00:45:00"

**Comment by stephan192** [comment]
Hi @dadosch, i cannot reproduce your issue,
on my two systems (live system on rpi4 and dev system on windows docker) the time zones are converted correctly.
Which time zone have you configured for your home assistant system? Mine are set to GMT+1.

![img1](https://github.com/stephan192/hochwasserportal/assets/62512016/4da6302d-834a-4ead-ae90-0b8011f8eea7)
![img2](https://github.com/stephan192/hochwasserportal/assets/62512016/73a6b49a-9d04-4938-a146-e612f3a14506)

**Comment by stephan192** [comment]
16:45 in zone UTC+1 is the same point in time als 15:45 in zone UTC.
But your screenshots show 17:45 (one hour in the wrong direction so to say), this is interesting.

About the DWD integration:
- The DWD integration normally retrieves timestamps in UTC with correctly set zone. [See here](https://github.com/stephan192/dwdwfsapi/blob/bab26c0e9d98f634b81f55905fa4dba1b128a188/dwdwfsapi/weatherwarnings.py#L285)
- But i would expect the timestamp of the DWD integration to be 16:04 not 17:04 when your browser is set to UTC

I'll start investigate if it possible to set the correct time zone for all timestamps. But i'm not 100% sure if this will fix your issue, because it may be caused by something else.

**Comment by stephan192** [comment]
Hi @dadosch, i just released v0.0.21, which should hopefully fix this issue.
Now all datetime objects have their timezone set to UTC.

**Comment by dadosch** [comment]
Thank you. I can confirm that the issue is fixed. Thank you very much again for this great integration :)

Fixed by https://github.com/stephan192/hochwasserportal/commit/0eb89949ac0267a0152538d255e47443ff557c78
