### ISSUE TITLE
Incorrect display values if no data is transmitted from the water level measuring point

### ISSUE THREAD

**Issue by bac1x** [stephan192/hochwasserportal#56]
### Home Assistant version

Core 2024.12.4 Supervisor 2024.12.0 Operating System 14.1

### Hochwasserportal integration version

1.0.1

### Affected pegel

NI_4849104

### What happened

No values were updated or transmitted for approx. 24 hours. The displayed values in the dashboard were negative values of - 888 cm at the water level. I can no longer say exactly what the warning level was I think ‘Unknown’ can you display a warning that no data has been transmitted or the last transmitted status with time and date?

### Reproduction steps

I can not reproduce unless you try to interrupt the connection where the data is obtained from the measuring point, maybe a programmer of the addon could do that.

sorry for my bad english

**Comment by stephan192** [comment]
Hi @bac1x, it happens from time to time that one or more pegel are down for some time. I just checked NI_4849104 and it seems to be fine again.

But never the less. This ticket adresses two topics in one.
1. Report an error if a sensor hasn't been updated for a while.
2. Values of -888 are shown.

Regarding 1:
I will not implement an error message or something similar, due to the different update intervals of the different state portals. You can implement something yourself be evaluating the "last update" sensor attribute.

Regarding 2:
I will try to figure out if -888 is always reported if a sensor has a problem. If it's true i will inhibit -888 as value and not update the "last update" value in this case.

**Comment by stephan192** [comment]
Hi @bac1x,

**Regarding 1:**
If i want to get informed if a sensor is down for certain time i would solve it via an automation. The following is a quick example to trigger something if the sensor is unavailable for 12hours.
![grafik](https://github.com/user-attachments/assets/5319b588-d818-4001-829b-8c17ed488a7b)

**Regarding 2:**
The new version **v1.0.2** of this integration sets the sensor to unavailable if -888 is reported as value for NI pegel.

Can you please confirm and close this issue.
