### ISSUE TITLE
HW_TXT and ZEIT parameters

### ISSUE THREAD

**Issue by Dennis1000** [stephan192/hochwasserportal#9]
Thank you for your nice integration.
Having HW_TXT and ZEIT parameters would be nice as well.

**Comment by stephan192** [comment]
The HW_TXT is already available via the Info attribute.

I didn't implement reading out the ZEIT value because its not encoded in any "normal" time format.
If you provide a formula to transfer the input e.g. "Heute, 5:40Uhr" to a "standard" Python datetime object we can talk about adding this feature.

**Comment by Dennis1000** [comment]
Agreed that "Heute, 5:40am" isn't pretty, but we live in a flood plain and a timestamp - however formatted - is pretty important with a water level (I know I have 12 hours to make flood preparations if the level rises above a certain level.). So this timestamp is better than none ;-)
It's more of a ZEIT_TXT attribute...

Thanks for poiting out the info attrib.

**Comment by stephan192** [comment]
For all seven currently supported regions the timestamps received from the different portals are used as "last update" value in HA. For the missing ones i'll try to implement it the same way.
